
name: Example Workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Use Secret
      run: echo "My secret key is ${{ secrets.MY_SECRET_KEY }}"
