

name: Example Workflow

on:
  push:
    branches: [main]

env:
  MY_VARIABLE: "Hello, world!"
  ANOTHER_VARIABLE: "123"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Use Variables
      run: |
        echo $MY_VARIABLE
        echo $ANOTHER_VARIABLE

