name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Greeting
        run: echo "${{ env.GREETING }} Welcome to GitHub Actions."

      - name: Print Working Directory
        run: |
          pwd
          ls -l
      - name: Run Custom Script
        run: |
          bash /home/runner/work/GithubAction_POC/GithubAction_POC/scripts/myscript.sh
