name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      # - name: Adding Script to my workflow
      #   run: |
      #     pwd
      #     ls -l
      #     ls
      # - name: Execute myscript.sh
      #   run: |
      #     bash /home/runner/work/GithubAction_POC/GithubAction_POC/scripts/myscript.sh

      - name: Use Secret
        run: |
          echo "My secret key is ${{ secrets.MY_SECRET_KEY }} "
          echo "My Variable key is ${{ secrets.MYVARIABLEKEY }} "
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn clean install -B package --file spring-boot-ems/pom.xml
      - name: runtest
        run: mvn test  -B package --file spring-boot-ems/pom.xml
      - name: Generate code coverage report
        run: |
          
          mvn jacoco:report   -B package --file spring-boot-ems/pom.xml
      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: spring-boot-ems/target/site/jacoco/index.html
      - name: check jacoco
        run: |
         pwd
         cd  /home/runner/work/GithubAction_POC/GithubAction_POC/spring-boot-ems/target
          ls
      - name: Send Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: '{"text": "Ajay ingale slack notification."}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MY_SLACK_SECREAT }}
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ./spring-boot-ems
          args: >
           -Dsonar.organization=ajayingale12345
           -Dsonar.projectKey=ajayingale12345_GithubAction_POC
           -Dsonar.sources=src/main
           -Dsonar.exclusions=**/*.java
           # -Dsonar.java.binaries=target/ 
           # -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
           # -Dsonar.coverage.jacoco.reportPaths=target/jacoco.exec

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
