name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Adding Script to my workflow
        run: |
          pwd
          ls -l

      - name: Execute myscript.sh
        run: |
          bash /home/runner/work/GithubAction_POC/GithubAction_POC/scripts/myscript.sh
      
      - name: Use Secret
        run: |
          echo "My secret key is ${{ secrets.MY_SECRET_KEY }} "
          echo "My Variable key is ${{ secrets.MYVARIABLEKEY }} "
     
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file spring-boot-ems/pom.xml
        
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Download SonarQube Scanner
          curl -sSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner-cli.zip
          unzip -qq sonar-scanner-cli.zip

          # Run SonarQube analysis
          ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://your-sonarqube-server:9000 \
            -Dsonar.login=$SONAR_TOKEN
