name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
   
    steps:
      - name: Adding Script to my workflow
        run: |
          pwd
          ls -l
          ls

    
      
      - name: Use Secret
        run: |
          echo "My secret key is ${{ secrets.MY_SECRET_KEY }} "
          echo "My Variable key is ${{ secrets.MYVARIABLEKEY }} "
     
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Execute myscript.sh
      #   run: |
      #     bash /home/runner/work/GithubAction_POC/GithubAction_POC/scripts/myscript.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file spring-boot-ems/pom.xml
        
      - name: send notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
         payload: |
          {
           "text": "Ajay ingale slack notification."
           }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.MY_SLACK_SECREAT}} 
